language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - os: osx
      osx_image: xcode10.2  # Python 2.7 & 3.7
      language: shell       # 'language: python' is an error on Travis CI macOS

install: python setup.py install
script: python -m unittest discover
