language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - { python: 3.7, dist: xenial, sudo: true }
    - os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS

install: python setup.py install
script: python -m unittest discover
